# Complete list of 100 unique dance animations for Highrise
DANCES = {
    1: "idle-dance-tiktok4",
    2: "dance-tiktok10",
    3: "idle-dance-tiktok2",
    4: "emote-attentive",
    5: "idle-dance-casual",
    6: "dance-blackpink",
    7: "dance-charli",
    8: "dance-tiktok8",
    9: "dance-tiktok2",
    10: "dance-tiktok5",
    11: "dance-weird",
    12: "dance-tiktok9",
    13: "dance-breakdance",
    14: "dance-sexy",
    15: "dance-vogueing",
    16: "dance-pennywise",
    17: "dance-russian",
    18: "emote-fashionweek",
    19: "idle-loop-sitfloor",
    20: "dance-anime",
    21: "dance-pinguin",
    22: "dance-kawai",
    23: "dance-tiktok7",
    24: "dance-smoothwalk",
    25: "dance-employee",
    26: "idle-uwu",
    27: "idle-toilet",
    28: "idle-wild",
    29: "emote-sleigh",
    30: "emote-snowangel",
    31: "emote-snowball",
    32: "emote-confused",
    33: "emote-teleporting",
    34: "emote-swordfight",
    35: "emote-punkguitar",
    36: "emote-zombierun",
    37: "emote-theatrical",
    38: "emote-icecream",
    39: "emote-victory",
    40: "emote-angry",
    41: "emote-cute",
    42: "emote-bow",
    43: "emote-curtsy",
    44: "emote-snowball",
    45: "emote-pose7",
    46: "emote-pose8",
    47: "emote-pose1",
    48: "emote-pose3",
    49: "emote-pose5",
    50: "emote-maniac",
    51: "emote-energyball",
    52: "emote-snake",
    53: "emote-frog",
    54: "emote-superpunch",
    55: "emote-superpose",
    56: "dance-tiktok4",
    57: "dance-robotic",
    58: "dance-salsa",
    59: "dance-sailor",
    60: "dance-shoppingcart",
    61: "dance-shuffle",
    62: "emote-hot",
    63: "emote-charging",
    64: "emote-pose10",
    65: "dance-martial-artist",
    66: "dance-weird2",
    67: "dance-creepypuppet",
    68: "dance-tiktok3",
    69: "dance-spiritual",
    70: "dance-headbang",
    71: "idle-dance-headbobbing",
    72: "emote-fall-backward",
    73: "emote-fall-forward",
    74: "emote-gravity",
    75: "emote-levitate",
    76: "emote-weird-dance",
    77: "emote-timejump",
    78: "emote-jumpb",
    79: "emote-summon",
    80: "emote-float",
    81: "emote-tornado",
    82: "emote-launch",
    83: "emote-jetpack",
    84: "emote-astronaut",
    85: "emote-split",
    86: "emote-headstand",
    87: "emote-cartwheel",
    88: "emote-backflip",
    89: "emote-frontflip",
    90: "emote-roll",
    91: "emote-peace",
    92: "emote-wave",
    93: "emote-clap",
    94: "emote-thumbsup",
    95: "emote-heart",
    96: "emote-kiss",
    97: "emote-laugh",
    98: "emote-cry",
    99: "emote-sleep",
    100: "emote-wake"
}

# Special dance mappings as requested
SPECIAL_DANCES = {
    1: "emote-relaxed",      # #Relaxed
    2: "emote-float",        # #GhostFloat  
    3: "idle-sleep",         # #CozyNap
    4: "dance-twerking"      # #TwerkItOut
}

def get_dance_by_number(number):
    """Get dance animation by number (1-100)"""
    if number in SPECIAL_DANCES:
        return SPECIAL_DANCES[number]
    return DANCES.get(number, "idle-dance-casual")

def get_all_dances():
    """Get all available dances"""
    return DANCES
